- name: Cleanup kubernetes folder
  file:
    state: absent
    path: "kubernetes/snapshot"
- file:
    path: kubernetes/snapshot
    state: directory


- name: prepare templates
  template:
    src: "{{ item }}"
    dest: kubernetes/snapshot/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - ../templates/snapshot/*.j2

- name: Deploy snapshot cronjob
  command: "kubectl apply -f kubernetes/snapshot -n {{ k8s_namespace }}"
